Models/Sida.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace KompaniInfo.Models
{
    public class Sida
    {
		public int Id { get; set; }

		[Required(AllowEmptyStrings = false, ErrorMessage = "Innehåll måste anges")]
		[Display(Name ="Innehåll")]
		public string Innehall { get; set; }

		[Required(AllowEmptyStrings = false, ErrorMessage = "Namn måste anges")]
		[MaxLength(100)]
		public string Namn{ get; set; }

	}
}

Controllers/SidaController.cs
using KompaniInfo.Repositories.Interfaces;
using KompaniInfo.Services;
using KompaniInfo.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace KompaniInfo.Controllers
{
    public class SidaController : Controller
    {
        private readonly ISidaRepository _context;
        public SidaController(ISidaRepository context)
        {
            _context = context;
        }

        public IActionResult Index(int id)
        {
            var sida = _context.Get(id);
            if (sida != null)
            {
                SidaTransform st = new SidaTransform();
                var vmSida = st.Transform(sida);
                return View(vmSida);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        public IActionResult GetLankarForMeny()
        {
            return PartialView("LankarTillSidor.cshtml", _context.GetLankarToSidor());
        }

        [Authorize(Roles = Roles.Admin)]
        public IActionResult Skapa()
        {
            return View();
        }

        [Authorize(Roles = Roles.Admin)]
        [HttpPost]
        public IActionResult Skapa(VMSida vmSida, string btn)
        {
            if (btn == "LaddaUppFil" && vmSida.Fil != null)
            {
                FilService service = new FilService();
                if (!service.ValideraFil(vmSida.Fil))
                {
                    ModelState.Clear();
                    ModelState.TryAddModelError("Fil", "Fel fil");
                    return View();
                }
                var fil = service.SparaFil(vmSida.Fil);
                _context.SparaBild(fil);
                ModelState.Clear();
                vmSida.Innehall += service.GetHtmlString(fil);
                return View(vmSida);
            }
            if (ModelState.IsValid)
            {
                SidaTransform st = new SidaTransform();
                var sida = st.Transform(vmSida);
                _context.Skapa(sida);
                return RedirectToRoute("sidor", new { Id = sida.Id });
            }
            else
                return View();
        }

        [Authorize(Roles = Roles.Admin)]
        public IActionResult Andra(int id)
        {
            var sida = _context.Get(id);
            if (sida != null)
            {
                SidaTransform st = new SidaTransform();
                var vmSida = st.Transform(sida);
                return View(vmSida);
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        [Authorize(Roles = Roles.Admin)]
        [HttpPost]
        public IActionResult Andra(VMSida vmSida, string btn)
        {
            if (btn == "LaddaUppFil" && vmSida.Fil != null)
            {
                FilService service = new FilService();
                if (!service.ValideraFil(vmSida.Fil))
                {
                    ModelState.Clear();
                    ModelState.TryAddModelError("Fil", "Fel fil");
                    return View();
                }
                var fil = service.SparaFil(vmSida.Fil);
                _context.SparaBild(fil);
                ModelState.Clear();
                vmSida.Innehall += service.GetHtmlString(fil);
                return View(vmSida);
            }
            if (ModelState.IsValid)
            {
                SidaTransform st = new SidaTransform();
                var sida = st.Transform(vmSida);
                _context.Andra(sida);
                return RedirectToRoute("sidor", new { Id = sida.Id });
            }
            else
                return View();
        }

        [Authorize(Roles = Roles.Admin)]
        public IActionResult TaBort(int id)
        {
            var sida = _context.Get(id);
            if (sida != null)
            {
                _context.TaBort(sida);
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }
    }
}

Views/Sida/Andra.cshtml
@model KompaniInfo.ViewModels.VMSida
@{
	ViewData["Title"] = "Ändra";
}

<h2>Ändra sida</h2>
<div class="row">
	<div class="col-md-8">
		<div class="input-group">
			<form asp-action="Andra" enctype="multipart/form-data">
				@Html.Partial("UpsertSida")
			</form>
		</div>
	</div>
	@Html.Partial("MarkDownSyntax");
</div>

Views/Sida/Index.cshtml
@using KompaniInfo.ViewModels
@model KompaniInfo.Models.Sida
	
<div class="post" style="margin-bottom: 120px;">
	<p>
		<h1>@Model.Namn</h1>
	</p>
	<markdown asp-markdown-for="@Model.Innehall"></markdown>

@if (User.Identity.IsAuthenticated && User.HasClaim(t => t.Type == System.Security.Claims.ClaimTypes.Role && t.Value == "Admin"))
{
	<div>
		@Html.ActionLink("Ändra", "Andra", "Sida", new { id = Model.Id })
		@Html.ActionLink("Ta bort", "TaBort", "Sida", new { id = Model.Id },
			new { onclick = "return confirm('Är du säker att du vill ta bort den här sidan?');" })
	</div>
}
</div>

Views/Sida/Skapa.cshtml
@model KompaniInfo.ViewModels.VMSida

@{
	ViewData["Title"] = "Skapa";
}

<h2>Skapa sida</h2>

<div class="row">
	<div class="col-md-8">
		<div class="input-group">
			<form asp-action="Skapa" enctype="multipart/form-data">
				@Html.Partial("UpsertSida")
			</form>
		</div>
	</div>
	@Html.Partial("MarkDownSyntax")
</div>